# Generated by Django 3.2.9 on 2022-07-16 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='会议室id')),
                ('meeting_name', models.CharField(max_length=100, verbose_name='会议室名称')),
                ('create_userid', models.IntegerField(max_length=10, verbose_name='创建用户id')),
                ('update_userid', models.IntegerField(max_length=10, verbose_name='修改用户id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=False, verbose_name='删除（是1/否0）')),
            ],
            options={
                'db_table': 'Meeting',
                'unique_together': {('meeting_name', 'is_delete')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='预定ID')),
                ('reserve_userid', models.IntegerField(max_length=10, verbose_name='预定用户id')),
                ('reserve_time', models.DateField(verbose_name='预定时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_id', to='app1.meeting', verbose_name='会议室id')),
            ],
            options={
                'db_table': 'Reserve',
                'unique_together': {('meeting_id', 'reserve_time')},
            },
        ),
    ]
