# Generated by Django 3.2.9 on 2022-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_userid',
            field=models.IntegerField(verbose_name='创建用户id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='update_userid',
            field=models.IntegerField(verbose_name='修改用户id'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_userid',
            field=models.IntegerField(verbose_name='预定用户id'),
        ),
    ]
